### ISSUE TITLE
git clone hangs, klaus reports an "Illegal seek" error

### ISSUE THREAD

**Issue by sbraz** [jonashaag/klaus#154]
Hi, I can't tell if this is an issue with klaus or dulwich but I am unable to clone my repositories using latest git versions of both modules.
`git clone http://127.0.0.1:8080/klaus/` hangs. This is what the server log shows:
```
./bin/klaus --debug --smarthttp  ~/klaus/                                                                                                                                      
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 433-449-159
127.0.0.1 - - [11/Apr/2016 12:17:10] "GET /klaus/info/refs?service=git-upload-pack HTTP/1.1" 200 -
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/sbraz/venv/lib/python2.7/site-packages/dulwich/web.py", line 242, in handle_service_request
    handler.handle()
  File "/home/sbraz/venv/lib/python2.7/site-packages/dulwich/server.py", line 335, in handle
    get_tagged=self.get_tagged)
  File "/home/sbraz/venv/lib/python2.7/site-packages/dulwich/repo.py", line 250, in fetch_objects
    wants = determine_wants(self.get_refs())
  File "/home/sbraz/venv/lib/python2.7/site-packages/dulwich/server.py", line 547, in determine_wants
    want = self.proto.read_pkt_line()
  File "/home/sbraz/venv/lib/python2.7/site-packages/dulwich/protocol.py", line 150, in read_pkt_line
    sizestr = read(4)
  File "/home/sbraz/venv/lib/python2.7/site-packages/dulwich/protocol.py", line 337, in read
    data = self._recv(left)
  File "/usr/lib64/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib64/python2.7/gzip.py", line 295, in _read
    pos = self.fileobj.tell()   # Save current position
IOError: [Errno 29] Illegal seek
127.0.0.1 - - [11/Apr/2016 12:17:10] "POST /klaus/git-upload-pack HTTP/1.1" 200 -
```
I think this might be related to https://github.com/jelmer/dulwich/issues/140 but I fail to see where exactly the issue is.

**Comment by jonashaag** [comment]
Which version of dulwich are you using here?

**Comment by jonashaag** [comment]
Hm, could you insert a debug print there to see what type `self.fileobj` is?
Also, maybe a few debug print here https://github.com/jelmer/dulwich/blob/master/dulwich/web.py#L373 might help to know if we're using a buffered file or `wsgi.input `here

**Comment by sbraz** [comment]
Here is `environ` just after https://github.com/jelmer/dulwich/blob/master/dulwich/web.py#L373
```
{'CONTENT_LENGTH': '638',
 'CONTENT_TYPE': 'application/x-git-upload-pack-request',
 'HTTP_ACCEPT': 'application/x-git-upload-pack-result',
 'HTTP_ACCEPT_ENCODING': 'gzip',
 'HTTP_CONTENT_ENCODING': 'gzip',
 'HTTP_HOST': '127.0.0.1:8080',
 'HTTP_USER_AGENT': 'git/2.8.0',
 'PATH_INFO': '/klaus/git-upload-pack',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': 46732,
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '127.0.0.1',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'Werkzeug/0.11.5',
 'httpauth.uri': '/klaus/git-upload-pack',
 'werkzeug.proxy_fix.orig_http_host': '127.0.0.1:8080',
 'werkzeug.proxy_fix.orig_remote_addr': '127.0.0.1',
 'werkzeug.proxy_fix.orig_wsgi_url_scheme': 'http',
 'werkzeug.request': <BaseRequest 'http://127.0.0.1:8080/klaus/git-upload-pack' [POST]>,
 'werkzeug.server.shutdown': <function shutdown_server at 0x7fe36f734a28>,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe3774b41e0>,
 'wsgi.input': <open file '<socket>', mode 'rb' at 0x7fe370245d20>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
```
In the gzip lib, `fileobj` is `<open file '<socket>', mode 'rb' at 0x7fe370245d20>`.
For some reason, `environ['wsgi.input']` has `seek` and `tell` attributes but they are not actually usable.

**Comment by jonashaag** [comment]
jelmer/dulwich#417 should fix this.

**Comment by sbraz** [comment]
I just tested your branch and although I don't see the error any more, clone still hangs. I'm not sure the seek/tell issue was even related.
I tried stracing git clone and I see:
```
[pid  3432] poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
[pid  3432] rt_sigaction(SIGPIPE, {SIG_DFL, [], SA_RESTORER, 0x7fc0898eda60}, NULL, 8) = 0
[pid  3432] select(4, [3], [], [], {0, 50000}) = 0 (Timeout)
[pid  3432] rt_sigaction(SIGPIPE, NULL, {SIG_DFL, [], SA_RESTORER, 0x7fc0898eda60}, 8) = 0
[pid  3432] rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER, 0x7fc0898eda60}, NULL, 8) = 0
[pid  3432] poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
[pid  3432] rt_sigaction(SIGPIPE, {SIG_DFL, [], SA_RESTORER, 0x7fc0898eda60}, NULL, 8) = 0
[pid  3432] select(4, [3], [], [], {0, 50000}) = 0 (Timeout)
[pid  3432] rt_sigaction(SIGPIPE, NULL, {SIG_DFL, [], SA_RESTORER, 0x7fc0898eda60}, 8) = 0
[pid  3432] rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER, 0x7fc0898eda60}, NULL, 8) = 0
[pid  3432] poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
[pid  3432] rt_sigaction(SIGPIPE, {SIG_DFL, [], SA_RESTORER, 0x7fc0898eda60}, NULL, 8) = 0
[pid  3432] select(4, [3], [], [], {0, 50000}) = 0 (Timeout)
[pid  3432] rt_sigaction(SIGPIPE, NULL, {SIG_DFL, [], SA_RESTORER, 0x7fc0898eda60}, 8) = 0
[pid  3432] rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER, 0x7fc0898eda60}, NULL, 8) = 0
[pid  3432] poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
[pid  3432] rt_sigaction(SIGPIPE, {SIG_DFL, [], SA_RESTORER, 0x7fc0898eda60}, NULL, 8) = 0
[pid  3432] select(4, [3], [], [], {0, 50000}
```
Where lsof shows:
```
git-remot 3432   sbraz    0r  FIFO       0,8      0t0 289273585 pipe
git-remot 3432   sbraz    1w  FIFO       0,8      0t0 289273586 pipe
git-remot 3432   sbraz    2u   CHR     136,8      0t0        11 /dev/pts/8
git-remot 3432   sbraz    3u  IPv4 289273591      0t0       TCP 127.0.0.1:59008->127.0.0.1:http-alt (ESTABLISHED)
git-remot 3432   sbraz    4w  FIFO       0,8      0t0 289273588 pipe
git-remot 3432   sbraz    5r  FIFO       0,8      0t0 289273589 pipe
```
I am trying to obtain more debugging info but I don't really know what is happening here.

**Comment by jonashaag** [comment]
Maybe try another repo, also use `GIT_TRACE=1; GIT_CURL_VERBOSE=1 git clone --verbose`

**Comment by sbraz** [comment]
I just deployed the app with gunicorn and it works. I think werkzeug is at fault here.

**Comment by sbraz** [comment]
As for git with debugging, it's simply not receiving a reply:
```
> POST /klaus/git-upload-pack HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: git/2.8.0
Accept-Encoding: gzip
Content-Type: application/x-git-upload-pack-request
Accept: application/x-git-upload-pack-result
Content-Encoding: gzip
Content-Length: 638

* upload completely sent off: 638 out of 638 bytes
```

**Comment by jonashaag** [comment]
Oh, hey, I can reproduce this; I'll have a look myself.

**Comment by sbraz** [comment]
FYI, It also hangs with uwsgi. Only gunicorn seems to work.

**Comment by jonashaag** [comment]
OK, jelmer/dulwich#418 should fix this.

**Comment by sbraz** [comment]
Thanks, I'll test this :) Do you plan on making a new release soon?

**Comment by sbraz** [comment]
Err… disregard my previous comment, I just realised there is nothing wrong with klaus itself. All the fixes are for dulwich.
However it would be nice to see a klaus release that works with Python 3 as the latest version doesn't.

**Comment by jonashaag** [comment]
> Err… disregard my previous comment, I just realised there is nothing wrong with klaus itself. All the fixes are for dulwich.

As soon as dulwich releases the fixes I will update the minimum required version in the dependencies.

> However it would be nice to see a klaus release that works with Python 3 as the latest version doesn't.

This is too an issue with dulwich, see jelmer/dulwich#295

**Comment by jonashaag** [comment]
This is now fixed in dulwich
